In [3]:
import os
import csv
import math
import pandas as pd

# 함수

# term frequency
def tf(t, d):
    return d.count(t)

# inverse docuent frequency
def idf(t):
    df = 0
    for doc in sdocs:
        df += t in doc
    return math.log(N / (df + 1))

# TF-IDF
def tfidf(t, d):
    return tf(t, d) * idf(t)

os.getcwd()
os.chdir('C:\\Users\\Leessx\\Desktop\\leezzx\\학교과제\텍스트마이닝')

# 데이터 로딩
f = open("삼성전자 주식 종목토론 방 15개 문서.txt", 'r', encoding='UTF8')
docs = f.read()
f.close()

sdocs = docs.split(",")
review_list = list(set(w for doc in sdocs for w in doc.split()))
review_list.sort()

# TF-IDF 계산
N = len(sdocs)

result = []
for i in range(N):
    result.append([])
    d = sdocs[i]
    for j in range(len(review_list)):
        t = review_list[j]
        
        result[-1].append(tfidf(t, d))
        
review_tfidf = pd.DataFrame(result, columns = review_list)
review_tfidf

,100만,10만,2000원대,300만,갈,같다,개인만,개인이,거품이다,공매도는,...,주식,주식으로,주식판에,찍는게,최근,하다,하락,헐,혼자쳐내렸으니,힘들것
0,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,2.014903,0.000000,0.000000,...,1.098612,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903
1,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.098612,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000
8,2.014903,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.098612,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.098612,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,...,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,2.014903,0.000000,0.000000,0.000000

In [10]:
# term frequency 계산
N = len(sdocs)

result = []
for i in range(N):
    result.append([])
    d = sdocs[i]
    for j in range(len(review_list)):
        t = review_list[j]
        
        result[-1].append(tf(t, d))
        
review_tf = pd.DataFrame(result, columns = review_list)
review_tf

# KMeans 군집분석
from sklearn.cluster import KMeans

model = KMeans(n_clusters = 2).fit(review_tf)

cl = model.fit_predict(review_tf)
review_tf['주식'] = cl
review_tf

,100만,10만,2000원대,300만,갈,같다,개인만,개인이,거품이다,공매도는,...,주식,주식으로,주식판에,찍는게,최근,하다,하락,헐,혼자쳐내렸으니,힘들것
0,0,0,0,0,0,1,0,1,0,0,...,1,1,0,0,0,0,0,0,0,1
1,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
5,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
6,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
8,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
12,0,1,0,0,0,0,0,0,1,0,...,1,0,0,1,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0